### ISSUE TITLE
command line interface to register hours

### ISSUE THREAD

**Issue by JamesReate** [integral-io/time-tracker#1]
These should probably be broken out into more issues:

- interactive mode: (set date, hours, project)
- arguments mode: just pass in the params.
- no args: defaults to 8 hours, today, and default project
- saves to json file in home directory
- export: saves csv with date, hours
- should accept decimal hours: 8.5 = 8h30m
- shortcuts when passing in date: 17 = defaults to current month, 08/17 = defaults to current year

**Comment by JamesReate** [comment]
https://github.com/oclif/oclif

multi command one?

https://www.npmjs.com/package/inquirer

great for options

**Comment by cocowmn** [comment]
These points covered by `refactor` branch on 2018-8-16
